/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sh.GUI;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import java.util.List;
import sh.Korrect;
import sh.ModelZY;
import sh.PoTexRasch;

/**
 *
 * @author Muzaffar
 */
public class PJFrame extends javax.swing.JFrame {

    private Graphics2D g;
    private Line2D lineBuffer;
    private Line2D coordBuffer;
    private Ellipse2D circBuffer;
    private Ellipse2D circBuffer2;
    private Ellipse2D circBuffer3;
    private Ellipse2D circBuffer4;
    private Ellipse2D circBuffer5;
    private Ellipse2D circBuffer6;
    private Ellipse2D circBuffer11;
    private Ellipse2D circBuffer21;
    private Ellipse2D circBuffer31;
    private Ellipse2D circBuffer41;
    private Ellipse2D circBuffer51;
    private Ellipse2D circBuffer61;

    private List<Line2D> lineContainer = new ArrayList();
    private List<Line2D> coordinates = new ArrayList();
    private List<Ellipse2D> circContainer = new ArrayList();
    private List<Ellipse2D> circContainer2 = new ArrayList();
    private List<Ellipse2D> circContainer3 = new ArrayList();
    private List<Ellipse2D> circContainer4 = new ArrayList();
    private List<Ellipse2D> circContainer5 = new ArrayList();
    private List<Ellipse2D> circContainer6 = new ArrayList();
    private List<Ellipse2D> circContainer11 = new ArrayList();
    private List<Ellipse2D> circContainer21 = new ArrayList();
    private List<Ellipse2D> circContainer31 = new ArrayList();
    private List<Ellipse2D> circContainer41 = new ArrayList();
    private List<Ellipse2D> circContainer51 = new ArrayList();
    private List<Ellipse2D> circContainer61 = new ArrayList();

    /**
     * Creates new form PJFrame
     */
    public PJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        m = new javax.swing.JLabel();
        _m = new javax.swing.JTextField();
        h_nas = new javax.swing.JLabel();
        _h_nas = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        _b_pl = new javax.swing.JTextField();
        gamma = new javax.swing.JLabel();
        _gamma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        _Cst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _Fist = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _h_b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        _E = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        m.setText("наклон, 1/m");

        _m.setText("2");

        h_nas.setText("Высота насыпи");

        _h_nas.setText("6");

        a.setText("Ширина основной площадки, м (b_pl)");

        _b_pl.setText("7.6");

        gamma.setText("Объемный вес грунта, т/м3");

        _gamma.setText("1.68");

        jLabel1.setText("Удельное сцепление");

        _Cst.setText("0.67");

        jLabel2.setText("Угол внутренного трения");

        _Fist.setText("31");

        jLabel3.setText("Высота балласта, h_b");

        _h_b.setText("0.35");

        jLabel4.setText("E");

        _E.setText("0.001");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h_nas)
                    .addComponent(a)
                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_m, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(_h_nas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(_h_b, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(_b_pl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gamma)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_gamma, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(_Cst)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_E, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m)
                    .addComponent(jLabel2)
                    .addComponent(_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(_h_nas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_nas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(_b_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(_h_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(_gamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(_Cst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(0, 498, Short.MAX_VALUE))
        );

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PoTexRasch.Peremennie(Double.parseDouble(_m.getText()),
                Double.parseDouble(_h_nas.getText()),
                Double.parseDouble(_b_pl.getText()),
                Double.parseDouble(_gamma.getText()),
                Double.parseDouble(_Cst.getText()),
                Double.parseDouble(_Fist.getText()),
                Double.parseDouble(_h_b.getText()),
                Double.parseDouble(_E.getText()));
//        popravka: for (int i = 0; i < PoTexRasch.zyM.length; i++) {
//            for (int j = 0; j < PoTexRasch.zyM[i].length; j++) {
//                PoTexRasch.ZY(i, j);
//            }
//        }
        PoTexRasch.Raschet();

        for (int i = 0; i < PoTexRasch.zyM.length; i++) {
            for (int j = 0; j < PoTexRasch.zyM[i].length; j++) {
                System.out.print(" " + i + ":" + j + " " + PoTexRasch.zyM[i][j].toString());
            }
            System.out.println("");
        }
//        Korrect.Korrect(PoTexRasch.k_d0_10(), PoTexRasch.k_d1_9());
//
//        for (int i = 0; i < PoTexRasch.zyM.length; i++) {
//            for (int j = 0; j < PoTexRasch.zyM[i].length; j++) {
//                if (i + j >= 11) {
//                    System.out.println("DA");
//                    PoTexRasch.ZY(i, j);
//                }
//            }
//        }
//        for (int i = 0; i < PoTexRasch.zyM.length; i++) {
//            for (int j = 0; j < PoTexRasch.zyM[i].length; j++) {
//                System.out.print(" " + i + ":" + j + " " + PoTexRasch.zyM[i][j].toString());
//            }
//            System.out.println("");
//        }
        //------Рисуем------
        g = (Graphics2D) jPanel1.getGraphics();

//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[10][0].getY() * 100) + 300, (PoTexRasch.zyM[10][0].getZ() * 100) + 300,
//                (PoTexRasch.zyM[9][1].getY() * 100) + 300, (PoTexRasch.zyM[9][1].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[10][0].getY() * 100) + 300, (PoTexRasch.zyM[10][0].getZ() * 100) + 300,
//                (PoTexRasch.zyM[10][1].getY() * 100) + 300, (PoTexRasch.zyM[10][1].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[10][1].getY() * 100) + 300, (PoTexRasch.zyM[10][1].getZ() * 100) + 300,
//                (PoTexRasch.zyM[9][1].getY() * 100) + 300, (PoTexRasch.zyM[9][1].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        ////////////
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[10][1].getY() * 100) + 300, (PoTexRasch.zyM[10][1].getZ() * 100) + 300,
//                (PoTexRasch.zyM[10][2].getY() * 100) + 300, (PoTexRasch.zyM[10][2].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[10][2].getY() * 100) + 300, (PoTexRasch.zyM[10][2].getZ() * 100) + 300,
//                (PoTexRasch.zyM[9][2].getY() * 100) + 300, (PoTexRasch.zyM[9][2].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        ////////////
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[9][1].getY() * 100) + 300, (PoTexRasch.zyM[9][1].getZ() * 100) + 300,
//                (PoTexRasch.zyM[8][2].getY() * 100) + 300, (PoTexRasch.zyM[8][2].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[9][1].getY() * 100) + 300, (PoTexRasch.zyM[9][1].getZ() * 100) + 300,
//                (PoTexRasch.zyM[9][2].getY() * 100) + 300, (PoTexRasch.zyM[9][2].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
//        lineBuffer = new Line2D.Double((PoTexRasch.zyM[9][2].getY() * 100) + 300, (PoTexRasch.zyM[9][2].getZ() * 100) + 300,
//                (PoTexRasch.zyM[8][2].getY() * 100) + 300, (PoTexRasch.zyM[8][2].getZ() * 100) + 300);
//        lineContainer.add(lineBuffer);
        ///////////////
        //система координат
        coordBuffer = new Line2D.Double(0, 300, 1000, 300);
        coordinates.add(coordBuffer);
        coordBuffer = new Line2D.Double(900, 200, 900, 600);
        coordinates.add(coordBuffer);
        //////////////

        System.out.println("-----b0--- " + PoTexRasch.B0());
        System.out.println("DLINA OTKOSA " + (Math.sqrt(Math.pow(PoTexRasch.zyM[0][10].getY(), 2) + Math.pow(PoTexRasch.zyM[0][10].getZ(), 2))));
        System.out.println("-----l--- " + Math.abs(PoTexRasch.zyM[30][10].getY()));
        for (int i = 0; i < PoTexRasch.zyM.length; i++) {
            for (int j = 0; j < PoTexRasch.zyM[i].length; j++) {
                double x = PoTexRasch.zyM[i][j].getY() * 500;
                double y = PoTexRasch.zyM[i][j].getZ() * 500;
                if (i + j == 10) {
                    circBuffer = new Ellipse2D.Double(-1 * x + 900 - 3, y + 300 - 3, 6, 6);
                    circContainer.add(circBuffer);
                }
                if ((i + j > 10) && (i <= 10 && j <= 10)) {
                    circBuffer2 = new Ellipse2D.Double(-1 * x + 900 - 3, y + 300 - 3, 6, 6);
                    circContainer2.add(circBuffer2);
                }
                if ((i >= 11 && i <= 20) && j == 0) {
                    circBuffer3 = new Ellipse2D.Double(-1 * x + 900 - 3, y + 300 - 3, 6, 6);
                    circContainer3.add(circBuffer3);
                }
//                if ((i == 11 || i == 12) && j != 0) {
                if ((i >= 11 && i <= 20) && (j != 0)) {
//pX = X * CosA + Y * SinA
//pY = Y * CosA - X * SinA
                    double xt = x * Math.cos(PoTexRasch.alf()) - y * Math.sin(PoTexRasch.alf());
                    double yt = y * Math.cos(PoTexRasch.alf()) + x * Math.sin(PoTexRasch.alf());
//                    System.out.println("Math.cos(PoTexRasch.alf()) " + Math.toDegrees(PoTexRasch.alf()));
                    circBuffer4 = new Ellipse2D.Double(-1 * x + 900 - 3, y + 300 - 3, 6, 6);
                    circContainer4.add(circBuffer4);
                }
                if (i > 20 && i - j < 20) {
                    double xt = x * Math.cos(PoTexRasch.alf()) - y * Math.sin(PoTexRasch.alf());
                    double yt = y * Math.cos(PoTexRasch.alf()) + x * Math.sin(PoTexRasch.alf());
                    circBuffer5 = new Ellipse2D.Double(-1 * x + 900 - 3, y + 300 - 3, 6, 6);
                    circContainer5.add(circBuffer5);
                }

                if (i > 20 && i - j == 20) {
                    circBuffer6 = new Ellipse2D.Double(-1 * x + 900 - 3, y + 300 - 3, 6, 6);
                    circContainer6.add(circBuffer6);
                }
                //////////////////////////////////////////
                /////////////////////////////////////////
                /////////////////////////////////////////
                double l = PoTexRasch.zyM[30][10].getY() + 900;
//                System.out.println("=====================" + (PoTexRasch.zyM[30][10].getY() - PoTexRasch.zyM[0][0].getY()));
                if (i + j == 10) {
                    circBuffer11 = new Ellipse2D.Double(x + l - 3, y + 300 - 3, 6, 6);
                    circContainer11.add(circBuffer11);
                }
                if ((i + j > 10) && (i <= 10 && j <= 10)) {
                    circBuffer21 = new Ellipse2D.Double(x + l - 3, y + 300 - 3, 6, 6);
                    circContainer21.add(circBuffer21);
                }
                if ((i >= 11 && i <= 20) && j == 0) {
                    circBuffer31 = new Ellipse2D.Double(x + l - 3, y + 300 - 3, 6, 6);
                    circContainer31.add(circBuffer31);
                }
//                if ((i == 11 || i == 12) && j != 0) {
                if ((i >= 11 && i <= 20) && (j != 0)) {
//pX = X * CosA + Y * SinA
//pY = Y * CosA - X * SinA
                    double xt = x * Math.cos(PoTexRasch.alf()) - y * Math.sin(PoTexRasch.alf());
                    double yt = y * Math.cos(PoTexRasch.alf()) + x * Math.sin(PoTexRasch.alf());
                    circBuffer41 = new Ellipse2D.Double(x + l - 3, y + 300 - 3, 6, 6);
                    circContainer41.add(circBuffer41);
                }
                if (i > 20 && i - j < 20) {
                    circBuffer51 = new Ellipse2D.Double(x + l - 3, y + 300 - 3, 6, 6);
                    circContainer51.add(circBuffer51);
                }

                if (i > 20 && i - j == 20) {
                    circBuffer61 = new Ellipse2D.Double(x + l - 3, y + 300 - 3, 6, 6);
                    circContainer61.add(circBuffer61);
                }
            }
        }
        for (int i = 0; i < circContainer.size(); i++) {
            g.draw(circContainer.get(i));
        }
        for (int i = 0; i < coordinates.size(); i++) {
            g.setColor(Color.blue);
            g.draw(coordinates.get(i));
        }
        for (int i = 0; i < circContainer2.size(); i++) {
            g.setColor(Color.red);
            g.draw(circContainer2.get(i));
        }
        for (int i = 0; i < circContainer3.size(); i++) {
            g.setColor(Color.GREEN);
            g.draw(circContainer3.get(i));
        }
        for (int i = 0; i < circContainer4.size(); i++) {
            g.setColor(Color.BLUE);
            g.draw(circContainer4.get(i));
        }
        for (int i = 0; i < circContainer5.size(); i++) {
            g.setColor(Color.GREEN);
            g.draw(circContainer5.get(i));
        }
        for (int i = 0; i < circContainer6.size(); i++) {
            g.setColor(Color.magenta);
            g.draw(circContainer6.get(i));
        }
        /////////////////////////////////////////////////////
        /////////////////////////////////////////////////////
        /////////////////////////////////////////////////////
//        for (int i = 0; i < circContainer11.size(); i++) {
//            g.draw(circContainer11.get(i));
//        }
//        for (int i = 0; i < coordinates.size(); i++) {
//            g.setColor(Color.blue);
//            g.draw(coordinates.get(i));
//        }
//        for (int i = 0; i < circContainer21.size(); i++) {
//            g.setColor(Color.red);
//            g.draw(circContainer21.get(i));
//        }
//        for (int i = 0; i < circContainer31.size(); i++) {
//            g.setColor(Color.GREEN);
//            g.draw(circContainer31.get(i));
//        }
//        for (int i = 0; i < circContainer41.size(); i++) {
//            g.setColor(Color.BLUE);
//            g.draw(circContainer41.get(i));
//        }
//        for (int i = 0; i < circContainer51.size(); i++) {
//            g.setColor(Color.GREEN);
//            g.draw(circContainer51.get(i));
//        }
//        for (int i = 0; i < circContainer61.size(); i++) {
//            g.setColor(Color.magenta);
//            g.draw(circContainer61.get(i));
//        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel1.update(g);
        lineContainer.clear();
        circContainer.clear();
        circContainer2.clear();
        circContainer3.clear();
        circContainer4.clear();
        circContainer5.clear();
        circContainer6.clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _Cst;
    private javax.swing.JTextField _E;
    private javax.swing.JTextField _Fist;
    private javax.swing.JTextField _b_pl;
    private javax.swing.JTextField _gamma;
    private javax.swing.JTextField _h_b;
    private javax.swing.JTextField _h_nas;
    private javax.swing.JTextField _m;
    private javax.swing.JLabel a;
    private javax.swing.JLabel gamma;
    private javax.swing.JLabel h_nas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel m;
    // End of variables declaration//GEN-END:variables
}
